- README.md
[Rendered](https://github.com/cdist-community/cdist-conf/blob/4nd3r/update_readme_vol2/README.md)
Related PRs:
cdist-community/cdist-core#7
cdist-community/cdist-extra#2
> update cdist-conf/README.md, vol 2

- type/__file/gencode-local
> __file: Print --source pre-exists conflict on stderr

- type/__uci/explorer/state
- type/__uci/gencode-remote
- type/__uci/man.rst
- type/__uci/manifest
- type/__uci_section/explorer/match
- type/__uci_section/explorer/options
- type/__uci_section/explorer/type
- type/__uci_section/gencode-remote
- type/__uci_section/man.rst
- type/__uci_section/manifest
Just some minor corrections and updates to the `__uci*` types.
> __uci*: Minor corrections

- type/__uci/explorer/state
This fixes a regression I introduced in #11.
It broke idempotency of the type.
(Sorry for that, I should've paid better attention to the comment just above the line...)
> __uci: Fix regression introduced by #11

- type/__file/gencode-local
- type/__file/gencode-remote
Fixes https://code.ungleich.ch/ungleich-public/cdist/pulls/331
Signed-off-by: Steven Armstrong <steven@armstrong.cc>
> __file: make file uploading and attribute changes more atomic

- type/__file/gencode-remote
From:
https://code.ungleich.ch/ungleich-public/cdist/commit/abbc7dfc376ffb6554bfaad2d5a6ec93955f235f
> __file: fix mv

- type/__systemd_unit/man.rst
- type/__systemd_unit/manifest
- type/__systemd_unit/parameter/boolean
Also replace `__config_file` with `__file`.
> __systemd_unit: add --drop-in

- type/__locale_system/manifest
- type/__sensible_editor/manifest
- type/__sshd_config/explorer/config_file
Make all types use the same `version_ge()` function.
> Unify version_ge() functions

- explorer/lsb_codename
- explorer/lsb_description
- explorer/lsb_id
- explorer/lsb_release
- explorer/machine_type
- explorer/os
- explorer/os_release
- explorer/os_version
- type/__apt_mark/explorer/state
- type/__apt_ppa/gencode-remote
- type/__ssh_authorized_key/gencode-remote
Import changes done in ungleich cdist since the fork ([7dd2d10](https://code.ungleich.ch/ungleich-public/cdist/src/commit/7dd2d1025ae3b005e5d44d11e1ca62536119f36c)).
I'm not sure about the `lsb_*` changes implemented for CheckPoint, since what they read is not LSB information.
> Import updates from ungleich cdist

- type/__file/man.rst
- type/__mount/man.rst
- type/__package_apk/man.rst
- type/__package_dpkg/explorer/pkg_state
- type/__package_dpkg/man.rst
- type/__package_pkg_openbsd/man.rst
- type/__sensible_editor/man.rst
- type/__systemd_service/man.rst
- type/__unpack/man.rst
While hacking a script to parse man.rst files I found some small typos and errors.
> Fix man.rst typos

- explorer/init
- explorer/machine_type
- explorer/os
- explorer/os_version
- type/__package/manifest
Adds core support for [Chimera Linux](https://chimera-linux.org).
> Add support for Chimera Linux

- type/__sensible_editor/explorer/editor_path
- type/__sensible_editor/explorer/group
- type/__sensible_editor/explorer/user_home
- type/__sensible_editor/man.rst
- type/__sensible_editor/manifest
Nothing major, just a little bit of clean up (updated copyright banner, syntax, and some minor simplifications in the code).
> __sensible_editor: lint

- explorer/disks
> explorer/disks: add support for Mac OS X

- type/__block/gencode-remote
- type/__file/gencode-local
- type/__key_value/files/remote_script.sh
- type/__line/gencode-remote
- type/__ssh_authorized_key/gencode-remote
- type/__sshd_config/gencode-remote
> Replace cdist suffix with skonfig in tempfile names

- explorer/os
Just a little experiment.
As described in the coding style draft 7.1 and 7.1.1 usage of `test` is favourable over `[ ]`.
> explorer/os: if: use test over [ ]

- type/__svn/explorer/mode
- type/__svn/explorer/state
- type/__svn/gencode-remote
- type/__svn/man.rst
Fixed some typos, little but of cleanup and replace `quote` function with `shquot`.
> __svn: Lint

- explorer/os
- explorer/os_version
- type/__hostname/gencode-remote
- type/__hostname/manifest
Global explorers and `__hostname` type.
> Basic CRUX support

- type/__localedef/gencode-remote
- type/__localedef/man.rst
- type/__localedef/manifest
Another one of my patch sets which have been lying around on my machine for too long.
> __localedef: Lint and proper quoting

- type/__package_opkg/explorer/pkg_status
The path got corrupted in ce2e312.
> type/__package_opkg: Fix lock file path

- explorer/os
- explorer/os_version
- type/__hostname/gencode-remote
- type/__hostname/manifest
- type/__hwclock/manifest
- type/__locale_system/manifest
- type/__localedef/gencode-remote
- type/__package/manifest
- type/__package_yum/gencode-remote
- type/__sensible_editor/manifest
- type/__sshd_config/manifest
- type/__start_on_boot/explorer/state
- type/__start_on_boot/gencode-remote
- type/__svn/manifest
- type/__sysctl/gencode-remote
- type/__sysctl/manifest
- type/__unpack/manifest
> Add support for Oracle (Enterprise) Linux
