type/__unpack/gencode-remote
This patch extends the `__unpack` type so send messages when it changes the target's state.
Use case: I'm having a type that uses `__download`+`__unpack` to install some "strange piece of software" and I need to execute a non-trivial script in `code-remote` when a new version of this software is installed on the target.  
There would probably be a possibility to include this script as `--onchange` but it would certainly not help readability.
=> __unpack: Send messages

explorer/cpu_cores
Not all architectures have a core id property.
It was introduced ~3.13 for x86.
Replacing it with counting processor lines should work on all architectures.
=> explorer/cpu_cores: Update /proc/cpuinfo parsing

type/__package_opkg/explorer/pkg_status, type/__package_opkg/gencode-remote
This PR fixes a logic error that is present in the `pkg_status` explorer.
It prints the `notpresent` flag when `opkg info` actually found a package, and does not print it when OPKG does not know about a package.
This logic is inverted in this PR (as it should be).
I also did some linting, implemented safer quoting of package names and fixed two minor issues that occurred with different versions of OpenWrt:
- older versions of Busybox (didn't check which exactly) don't like it using `readonly` and immediately assigning a variable.
- On OpenWrt 19.07 the `opkg info` command seems to never print anything.
=> __package_opkg: Run opkg update when necessary

type/__link/explorer/state, type/__uci/explorer/state, type/__uci/files/uci_apply.sh, type/__user/gencode-remote, type/__user/manifest
While trying to configure more OpenWrt devices I stumbled over some cases that didn't work properly.
The ones I found are fixed in this PR.
**__uci**:
- On old OpenWrt releases the `PATH` was set incorrectly when running scripts via `ssh root@openwrt /bin/sh -c` (as cdist does).
This problem is not limited to OpenWrt, though, so maybe we'd want to solve the issue of setting the `PATH` correctly in cdist-core.
**__user**:
- OpenWrt does not have a `/home` by default, leading to failure when the `__user` type is used to manipulate non-root users.
- There were also `PATH` issues here.
To not introduce any more code duplication, I rewrote `gencode-remote` and extracted handling of the specialties for FreeBSD and OpenWrt into a separate `do_user` function.
**__link**:
- The `__link` type has …
=> Misc. fixes primarily for OpenWrt

explorer/disks
Adds disks detection code for Solaris.
Tested on:
* Sun Solaris 10 10/09*
* Oracle Solaris 11.2
* OmniOS CE v11 r151030v
* OpenIndiana Hipster 20190511
* Tribblix m17
on i86pc.
*) only works with `/usr/xpg4/bin/sh` which is an issue for other parts of cdist, too.
=> explorer/disks: Add Solaris support

explorer/os_version
Devuan stable releases store the codename and not the version number in `/etc/devuan_version`, unlike Debian's `/etc/debian_version`.
Has been tested on Devuan 1-4 (jessie-chimaera) and daedalus/ceres (which contains an incorrect codename in `/etc/devuan_version`, but the code works).
=> explorer/os_version: Fix for Devuan stable

type/__user/gencode-remote
PR #14 introduced a bug in the `__user` type that led to some arguments being quoted twice.
Fixes #21.
=> __user: Fix double quotation

type/__acl/gencode-remote, type/__acl/man.rst
tldr: `X` shouldn't be used to compare perms (getfacl), but only for setting (setfacl).
=> [__acl] fix handling special case of "X" in perms field

type/__sed/gencode-remote
Fixes `"$sed_cmd"` failing when `--regexp-extended` is used.
=> [__sed] don't use quoting around $sed_cmd for local exec

type/__download/explorer/remote_cmd_get, type/__download/gencode-local
`wget` really spams with it's progress output, mostly because it's send a new line each time it changes. This will use a bit more unneceesary bandwith for the ssh session for this useless feature.
Because there wasn't another option, `wget` is now quiet by default, just like `curl` does now. Should be ok to only output on error. Can't speak for `fetch` how verbose it is.
=> __download: silent wget output and progress status

type/__file/gencode-remote, type/__file/man.rst
Again I stumbled on situation where in one system, file which I want to get rid of, is real file and in another it's actually symlink (due to various legacy and non-technical reasons). It's not possible to use `__link` in my situation because I don't know the `--source`.
I think it makes totally sense to also remove symlinks if `--state absent`, because you don't care if it's real file or symlink - you just want that file gone.
=> __file: if state=absent, remove symlinks too

type/__download/gencode-local, type/__download/gencode-remote
Happend to me to download a very big file, which overflows `/tmp`. This will name the temp file similar to the original except the random pattern `mktemp` appends.
If this isn't much distinguishable, we can add more to the filename.
Currently it's only done for remote downloads, not for local ones. If the same should be done for local downloads, then it's a question where to download the files.
=> __download: change tmpfile to be in the destdir

type/__file/gencode-local
Still not a fan of the changes to the `__file` type but I'm making a PR to stay consistent with cdist-ungleich.
Hopefully this version is less broken than the previous one :-)
I'm not sure if the `mktemp -u` hack to prefix the template with `/__cdist` really works…
Is it granted that every user on every config host has read (and write?) access to `/`?
=> __file: Fixup to #36

type/__git/manifest
Trying to clone a Git repo over HTTPS fails on Debian if ca-certificates is not installed.
The problem might also apply to other OSes, but I haven't tested that.
=> __git: Install ca-certificates for https repos on Debian

type/__unpack/gencode-remote, type/__unpack/man.rst, type/__unpack/manifest
Copy of ungleich/cdist#785.
Original description:
> `cdist/conf/type/__unpack/manifest` already had a case for `.txz` but it was missing from the gencode-local code. Also added .bz2 support while here.
> 
> Ran into this as FreeBSD base sets are distributed as `.txz` files.
=> Extend __unpack cases to support .txz and .tbz2

type/__apt_source/files/source.list.template, type/__apt_source/man.rst, type/__apt_source/manifest, type/__apt_source/parameter/optional, type/__apt_source/parameter/optional_multiple
Allow users to specify a GPG key fingerprint or keyring file to be
included as the 'signed-by' option.
=> Handle signed-by option in __apt_source

type/__apt_source/files/source.list.template
The previous version failed if either `$forcedarch` or `$signed_by` was not set.
=> __apt_source: Fix source.list template for set -u

type/__package_apt/explorer/state
With this change the type can reinstall a package if the version that is
currently installed originates from a different release repository than is
provided by `--target-release`.
The comparison logic is unfortunately complex because APT doesn't provide a sensible interface to acquire such information.
Repositories are compared using their `Suite` attribute because the same repository can be addressed using different names (e.g. `bullseye-backports` and `stable-backports`).
One caveat is that the logic only works if the currently installed packages are up to date.
If the currently installed version is an old version which has been removed from the repository already, the type will not reinstall it because it cannot determine which repository the package originated from at installation …
=> __package_apt: Implement switching target release for installed packages.

type/__apt_source/files/source.list.template, type/__apt_source/manifest
Fixing the problem in the manifest and the template that caused the issues, hence undoing the previous fix.
Original implementation by @fancsali failed to export appropriate variables (`signed_by` and `forcedarch`) from the manifest to the template, so the template was missing those every time - whether the actual parameters have been provided in the first place or not.
The missing or unset variables in the template caused an issue anyway, as the template is coded in a defensive way, and forces variables to be set by calling `set -u`.
The immediate issue of the template failing was addressed in 2277ec5 by @sideeffect42 when merging the code.
However, I discovered the original issue of the parameters never making through (even if set) recently - which essentially made those completely …
=> Clean up missing variables issue in __apt_source

type/__apt_source/files/source.list.template
Okay, ladies and gents, please don't kill me... 😳 
Turns out, this works
```
bash$ sh -e -u
$
```
However, saying the same on a shebang line in a file
```
#!/bin/sh -e -u
...
```
and then running it, would return an error:
```
./test.sh
sh: 0: Illegal option -
```
=> Fix shebang line

type/__link/explorer/state, type/__link/explorer/type
When using `__link` to create a symbolic link with a non-existing `--source` (e.g. one being created by a cron job), the `type` explorer will always (incorrectly) report `none`, making the type recreate the symbolic link on every run.
This is because `test ! -e` returns `0` for a symbolic link whose link destination does not exist. So to fix the behaviour, we `test -h` first, detecting it is a symbolic link.
I also did a little simplification in the `state` explorer: we don't need to `cd` in the `--type symbolic` case, because the sources are compared as strings, not as actual file system paths.
=> __link: fix type explorer for symbolic links with missing source

explorer/os, explorer/os_version, type/__locale/manifest, type/__localedef/gencode-remote, type/__package/manifest, type/__package_yum/gencode-remote, type/__sshd_config/manifest, type/__start_on_boot/explorer/state, type/__start_on_boot/gencode-remote, type/__svn/manifest, type/__sysctl/gencode-remote, type/__sysctl/manifest, type/__unpack/gencode-remote, type/__unpack/manifest
This PR adds `os` definitions for the CentOS-descendants [AlmaLinux](http://almalinux.org), [Rocky Linux](http://rockylinux.org) and [EuroLinux](https://en.euro-linux.com).
I also updated the `case`s in all base types.
=> Add AlmaLinux, EuroLinux, Rocky Linux distributions

type/__cdistmarker/deprecated, type/__skonfigmarker/gencode-remote, type/__skonfigmarker/man.rst, type/__skonfigmarker/parameter/default/destination, type/__skonfigmarker/parameter/optional
We're using skonfig now, aren't we? Yet, we still use the `cdist-configured` marker file.
I propose to replace `__cdistmarker` with `__skonfigmarker` which creates a `/etc/skonfigured` marker file, instead.
Currently, the `__skonfigmarker` in this PR still creates `/etc/cdist-configured` in addition if the user does not use the `--destination` parameter.
=> __skonfigmarker: New type

type/__apt_backports/manifest
At least Devuan adds the unstable suffix to the `VERSION_CODENAME` in `/etc/os-release`.
This results in the type creating an APT source with an unexpected name, e.g. `/etc/apt/sources.list.d/daedalus ceres-backports.list`.
This PR fixes this by only using the first word of the codename string.
What is left unsolved is the behaviour on pre-release distributions which don't usually have backports.
Devuan is an exception to this rule. Currently, there is [testing-backports](http://deb.devuan.org/merged/dists/testing-backports/) for Devuan because Debian has released a new version while Devuan has not yet.
=> __apt_backports: fix for unstable releases

type/__package_apt/gencode-remote
If a user uses `__package_apt` on Devuan ceres e.g. like this:
```sh
__package_apt foo \
--target-release "$(cat "${__global:?}/explorer/lsb_codename")-backports
```
It results in the following error message:
```
code-remote:stderr
------------------
E: Unable to locate package ceres-backports
```
The reason for this being that lsb_codename on Devuan ceres contains two words (e.g. `daedalus ceres`).
Word expansion on the target then converted the second word "ceres-backports" into a separate argument which got interpreted by apt-get(8) as the package.
This simple patch quotes the target release, resulting in an error message which makes more sense:
```
code-remote:stderr
------------------
E: The value 'daedalus ceres-backports' is invalid for APT::Default-Release as such a release is not …
```
=> __package_apt: quote `--target-release`

type/__ssh_authorized_key/files/genentry.awk
Unlike gawk and mawk, nawk treats slashes in a character group as the end of a regex.
```console
$ for awk in gawk mawk nawk; do echo $awk:; echo 'ssh-rsa AAAAabc' | $awk '/^ssh-[^ ]+ AAAA[A-Za-z0-9+/=]+$/'; done
gawk:
ssh-rsa AAAAabc
mawk:
ssh-rsa AAAAabc
nawk:
nawk: nonterminated character class ^ssh-[^ ]+ AAAA[A-Za
source line number 1
context is
/^ssh-[^ ]+ >>>  AAAA[A-Za-z0-9+/ <<<
```
=> __ssh_authorized_key: genentry: fix regex for nawk

type/__download/explorer/remote_cmd_get, type/__download/explorer/remote_cmd_sum, type/__download/explorer/state, type/__download/files/common.sh, type/__download/gencode-local, type/__download/gencode-remote, type/__download/man.rst, type/__download/manifest
This PR  replaces `__remote_copy` with `__remote_exec` (preparation for skonfig/skonfig#74) in `__download`.
While doing this I noticed that there is some code duplication which I tried to resolve by merging common gencode functionality to download files and check sums into `files/common.sh` and reuse the code in the explorers to also detect `cmd_{get,sum}` for local execution.
=> __download: reduce code duplication, replace `__remote_copy`

explorer/os, explorer/os_version
As reported by @lunarnull the `os` explorer detects `guixsd` also on other operating systems where the Guix package manager is installed.
So I did three changes:
1. moved the `guixsd` section to the very bottom. If somebody uses a very strange OS with the Guix package manager installed it would still be misclassified, but maybe that's still better than an error?
2. reorganised the blocks into groups by heritage,
3. added basic support for `pop-os` while at it.
Newer versions of GNU Guix also have a `/etc/os-release` file which reports `guix`.
These systems would now be detected as `guix` instead of `guixsd` which is a backwards incompatible change.
(The system is called just Guix (or Guix System) now. The old name Guix SD was only used up to version 1.0.)
I don't think it makes sense …
=> Fix miscategorisation of systems with Guix package manager as GNU Guix OS, add basic detection for Pop!_OS

type/__start_on_boot/explorer/state
`"/etc/runlevels/${d}/${name}"` expands to `"/etc/runlevels//etc/runlevels/${level}/${name}"`.
Also change `test -f` to `test -e` because `/etc/runlevels` contains symlinks.
=> __start_on_boot: Fix state explorer for OpenRC

type/__pyvenv/explorer/group, type/__pyvenv/explorer/owner, type/__pyvenv/explorer/state, type/__pyvenv/gencode-remote, type/__pyvenv/manifest
Just a little patch to check if the venv directory exists before trying to run `ls(1)` on in in the `owner` and `group` explorers.
Also, while in there I added missing copyright headers and updated the exsting ones.
=> __pyvenv: Don't ls a non-existing directory

type/__package_apt/explorer/state
When trying to remove already absent package which has reverse provides defined, and reverse provide is installed, then that gets removed.
For example with vim:
```
$ dpkg -l | awk '/vim/ {print $2}'
vim-common
vim-gtk3
vim-gui-common
vim-runtime
$ echo __package_apt vim --state absent | skonfig localhost -i - -n 
INFO: localhost: Starting dry run
INFO: localhost: Processing __package_apt/vim
INFO: localhost: Finished dry run in 1.44 seconds
$ skonfig -d localhost | grep code-remote
object/__package_apt/vim/.cdist-r4dzn92m/code-remote: DEBIAN_FRONTEND=noninteractive apt-get --quiet --yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" remove  'vim-gtk3'
```
Proposed change fixes this.
=> __package_apt: only check rprovides if requested state is "present"

type/__clean_path/man.rst
Fixed a typo (parameter `not-type` was incorrectly called `rm-type`) and added an example to clear everything inside a given directory (I think it was not entirely clear how to do so just by reading the man page).
=> __clean_path: update man.rst

type/__rsync/man.rst
Some parameters require a certain minimum version of rsync to function.
I added this information to the man.rst.
The required versions have been released already years ago, but unfortunately some operating systems (hello, macOS) didn't update in years because of the GPL-3 controversy.
Adding this information should make it clear for affected users that the parameters cannot be used.
=> __rsync: Document minimum rsync versions in man.rst

type/__rsync/gencode-local
Different versions of rsync output different lengths of `--itemize-changes` lists.
Also, catch the special form "*deleting".
e.g. on macOS:
2.6.9
*deleting xyz
.d..t.... ./
<f+++++++ foo
3.2.1-3.2.2
*deleting   xyz
.d..t........ ./
<f+++++++++++ foo
3.2.3-3.3.0
*deleting   xyz
.d..t....... ./
<f++++++++++ foo
=> __rsync: Be flexible in the length of `--itemize-changes` output

explorer/is-freebsd-jail
The explorer is likely unused in 99% of all cases. It's certainly not used by any upstream types.
Futhermore, the same information can be extracted from the machine_type explorer:
```sh
grep jail "${__global:?}/explorer/machine_type"
```
=> Drop is-freebsd-jail explorer

explorer/init, explorer/machine_type, type/__file/explorer/cksum, type/__hostname/explorer/max_len, type/__hostname/gencode-remote, type/__hostname/manifest, type/__localedef/gencode-remote, type/__package_apt/gencode-remote, type/__user/explorer/shadow
`test -a` and `test -o` have been removed from the POSIX.1-2024 standard.
I think we should thus also remove usage from skonfig.
https://pubs.opengroup.org/onlinepubs/9799919799/utilities/test.html#tag_20_121_25
=> Replace test -a, -o

type/__systemd_unit/manifest
Same filename is used when you do `systemctl edit unit`.
=> __systemd_unit: rename cdist.conf drop-in to override.conf (systemd default)

type/__systemd_unit/gencode-remote
Note to self: this type is out of hand and messy, should rewrite it.
This is actually fix and I'm confused why I haven't noticed this problem before.
If I disable unit, then I expect unit to be stopped, right? Well, now it is like this.
=> __systemd_unit: stop unit if state=disabled and --restart

explorer/os, explorer/os_version
Implement support for [Adélie Linux](https://www.adelielinux.org/) in global explorers.
I only updated `os` and `os_version` because it's just a standard Linux distribution, so the others should not require any changes for Adélie.
=> explorer: Detect Adélie Linux

explorer/cpu_cores, explorer/disks, explorer/init, explorer/interfaces, explorer/machine, explorer/memory, explorer/os, explorer/os_version
This is more of experimental nature, but still cool to show what skonfig can run on.
Support for the Haiku OS is implemented in the global explorers (modulo `machine_type`).
Haiku R1/beta has been tested and returns sensible values.
Some of the core types could be supported as well in the future.
BeOS has been added more or less as well, but I could only manually test it, because neither BeOS R5 nor Zeta wanted to boot in QEMU/VirtualBox.
I could get it running on actual hardware, but R5 does not support the network card and for Zeta I only have a Live CD which does not want to network because `/` is read-only, so...
SSHd should be possible, but doesn't make much sense without networking.
=> explorer: Initial Haiku/BeOS support

explorer/hostname, explorer/init, explorer/lsb_codename, explorer/lsb_description, explorer/lsb_id, explorer/lsb_release, explorer/runlevel, type/__git/explorer/group, type/__group/explorer/group, type/__group/explorer/gshadow, type/__hostname/explorer/max_len, type/__key_value/explorer/state, type/__key_value/files/remote_script.sh, type/__package/explorer/pkgng_exists, type/__package_apt/gencode-remote, type/__ssh_authorized_keys/explorer/file, type/__ssh_authorized_keys/explorer/group, type/__ssh_dot_ssh/explorer/group, type/__ssh_dot_ssh/explorer/passwd, type/__user/explorer/group, type/__user/explorer/passwd
Old versions of bash print an error message to stderr if the command cannot be found which clobbers stderr and skonfig dump unnecessarily with useless error messages:
stderr/remote: /var/lib/skonfig/conf/explorer/lsb_codename: line 1: command: lsb_release: not found
stderr/remote: /var/lib/skonfig/conf/explorer/lsb_id: line 1: command: lsb_release: not found
stderr/remote: /var/lib/skonfig/conf/explorer/lsb_description: line 1: command: lsb_release: not found
stderr/remote: /var/lib/skonfig/conf/explorer/lsb_release: line 1: command: lsb_release: not found
=> Silence stderr for command -v

explorer/os_version, type/__hostname/manifest, type/__hwclock/manifest, type/__locale_system/manifest, type/__localedef/gencode-remote, type/__start_on_boot/gencode-remote
For some operating systems the explorer result varied between operating systems. For some, a whole release file was printed, making output expecially hard to parse by other types.
* BeOS: Try to report userland version (libbe.so) if possible, fall back to uname -r. libbe.so version is more fine grained (e.g. R5.0.3) over uname -r (5.0).
* Haiku: Strip leading R from version.
* Fedora/Red Hat: report only version number, no more distro name and release codename.
* OpenWrt: report version number for all releases. For 17.01 and later a (pretty useless) commit ID was reported.
* SuSE: report only version number, no more whole SuSE-release/os-release.
* Slackware: Strip Slackware prefix, version number only.
* others: extract VERSION_ID from /etc/os-release if available.
Ordered case labels …
=> explorer/os_version: Report only version numbers

type/__uci_section/files/option_state.awk
When values contain single quotes, `sub()` only removes the first embedded quote.
e.g. in `/etc/config/openvpn`:
option tls_version_min '1.2 '\''or-highest'\'''
was unquoted to: `1.2 'or-highest'\''`
instead of: `1.2 'or-highest'`
=> __uci_section: Fix unquoting UCI values

explorer/cpu_sockets
Without proper anchors, the word "processor" in e.g. "Common KVM processor" is also counted as a CPU socket. This is, of course, incorrect.
~ # grep -cF 'processor' /proc/cpuinfo
2
~ # grep -F 'processor' /proc/cpuinfo
processor	: 0
model name	: Common KVM processor
This commit uses the same grep(1) command which is also used in cpu_cores as a fallback.
=> explorer/cpu_sockets: Fix counting for QEMU processor models

type/__uci/gencode-remote
Passing data to wc(1) via stdin stops it from printing the input file name.
This fixes:
object/__uci/.../stderr/gencode-remote: .../type/__uci/gencode-remote: 48: test: Illegal number: 1 /tmp/.../parameter/value
=> __uci: Fix line count

CODING_STYLE.md
I propose to document the shell guidelines we have mostly been following in recent times already to make it easier also for outside contributors to follow and understand why certain things are the way they are.
I tried to prove technical argumentation with references to the POSIX standard.
For the references I used the latest 2024 revision of POSIX even though there are currently no certified systems.
Closes #1.
=> Add CODING_STYLE.md

explorer/disks, explorer/init, explorer/os, explorer/os_version, type/__cron/explorer/cron-allowed, type/__cron/explorer/entry, type/__hostname/gencode-remote, type/__hostname/manifest, type/__locale_system/manifest, type/__sysctl/manifest
Granted, it may seem to come at the [worst possible time](https://www.synology.com/en-eu/company/news/article/DACH_VL_plus/Synology%20is%20increasingly%20relying%20on%20its%20own%20ecosystem%20for%20upcoming%20Plus%20models).
This PR has been in the works for some time already and I think it would be a shame to throw it away just because of one bad press release.
So here it is: basic support for Synology DSM.
Users and groups have not been touched, yet, because they would require quite some changes in the existing code.
Since larger changes are also required for improved support of other operating systems like Mac OS X or AIX, it makes more sense to add DSM support then (if I still have the motivation).
Support for DSM < 6.0 is partial.
* DSM < 6.0 is missing the `command` command and …
=> Add basic support for Synology DSM

type/__apt_source/files/source.list.template, type/__apt_source/gencode-remote, type/__apt_source/man.rst, type/__apt_source/manifest, type/__apt_source/parameter/optional, type/__apt_source/parameter/optional_multiple
This type is currently broken due to a regression introduced by 1e61371.
This PR further replaces remaining occurrences of cdist, makes `--arch` and `--component` multiple parameters which is cleaner from a skonfig-user view, adds codename detection from `os-release(5)` instead of just "legacy" LSB and some linting, typo corrections.
=> __apt_source: Fix regression and lint

type/__rsync/gencode-local, type/__rsync/gencode-remote, type/__rsync/man.rst
Unlike documented in [man.rst](https://github.com/skonfig/base/blob/07840f61914adf7fbc1eac599ec7691efbd26874/type/__rsync/man.rst?plain=1#L55), the `--onchange` commands were actually run on the config host.
This commit fixes this by moving this part of the code from `gencode-local` to `gencode-remote`.
To detect if `code-local` actually performed a sync `gencode-remote` checks for the "synced" message emitted by `gencode-local`.
Example:
```console
$ mkdir /tmp/xyz
$ (cd /tmp/xyz && touch foo bar baz)
$ echo '__rsync /tmp/rsynctest --source /tmp/xyz --onchange "echo synced >/tmp/foo" | skonfig -i- openbsd-77.vm
INFO: openbsd-77.vm: Starting configuration run
INFO: openbsd-77.vm: Processing __packge_pkg_openbsd/rsync
INFO: openbsd-77.vm: Processing __rsync/tmp/rsynctest
INFO: …
```
=> __rsync: Run `--onchange` on the target

explorer/os
Adopt the rc_getvar() function to parse the os-release(5) file instead of using eval to parse a file which could in theory contain (malicious) code.
Further, get rid of an ugly regex to match SuSE derivatives which fails to evaluate in some implementations of grep(1) due to the alternatives (e.g. OpenBSD).
(The code for rc_getvar was already used in the explorer to extract the `ID`, but it now reused to also handle `ID_LIKE`.)
=> explorer/os: Adopt rc_getvar() to parse os-release(5)

type/__locale_system/manifest
Fresh images.
22.04 (Jammy):
```
root@test-jammy:~# stat /etc/default/locale | head -1
File: /etc/default/locale
```
24.04 (Noble):
```
root@test-noble:~# stat /etc/default/locale | head -1
File: /etc/default/locale -> ../locale.conf
```
Sometime between 22.04 and 24.04 they pulled in change from Debian testing (Trixie).
Maybe some other release in between these two had that sooner, but I'm too lazy to check.
=> [__locale_system] ubuntu 23.10+ uses /etc/locale.conf

explorer/cpu_cores, explorer/cpu_sockets, explorer/memory
`explorer/{cpu_cores,cpu_sockets}`:
Assume that multiple processors are cores instead of sockets.
For most architectures sockets are not reported using "physical id" in `/proc/cpuinfo`, making this explorer report all cores as separate sockets.
This does not make much sense. For most systems assuming one socket and N cores seems to be more correct to me.
On NetBSD `/proc/cpuinfo` is only implemented for a few architectures.
For all the others `/proc/cpuinfo` is an empty file (which makes `grep -c` exit 1).
On NetBSD also currently no architecture reports "physical id", so socket detection using `/proc/cpuinfo` will never work.
It is thus disabled on NetBSD until somebody finds another way.
NetBSD also has `hw.ncpuonline` like OpenBSD (in fact, OpenBSD imported the code for it from …
=> explorer/{cpu_cores,cpu_sockets,memory}: Misc. fixes for NetBSD

explorer/cpu_cores, explorer/cpu_sockets, explorer/os, explorer/os_version, type/__package/manifest
SmartOS is an Illumos distribution, however its configuration differs quite a bit from regular Solaris (more of an "appliance"-style configuration). So we consider it a different operating system.
=> Detect SmartOS
